package com.point.cart.model;

public class AbnormalCartPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.media_id
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.modified_person
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String modifiedPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.modified_time
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.create_person
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.create_time
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.department
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_1
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_2
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_3
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_4
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_5
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_6
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_7
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String retain7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_8
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer retain8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_9
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer retain9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.retain_10
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer retain10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.adcode
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String adcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.province
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.city
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.area
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.property_number
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String propertyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.dev_name
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String devName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.media_resource_status
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String mediaResourceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.dev_type
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String devType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.dev_version
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String devVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.dev_install_model
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String devInstallModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.mac
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.address
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.s_lant
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String sLant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.resolution
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String resolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.trade
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String trade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.seller_name
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.seller_type
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String sellerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.business_area
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String businessArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.avg_price
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Integer avgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.network
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String network;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.quality
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String quality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.daily_customer_flow
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Double dailyCustomerFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.photo
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private Object photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.enterpriseStatus
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String enterprisestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_device_abnormal_information.fault
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    private String fault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.media_id
     *
     * @return the value of media_device_abnormal_information.media_id
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.media_id
     *
     * @param mediaId the value for media_device_abnormal_information.media_id
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.modified_person
     *
     * @return the value of media_device_abnormal_information.modified_person
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getModifiedPerson() {
        return modifiedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.modified_person
     *
     * @param modifiedPerson the value for media_device_abnormal_information.modified_person
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setModifiedPerson(String modifiedPerson) {
        this.modifiedPerson = modifiedPerson == null ? null : modifiedPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.modified_time
     *
     * @return the value of media_device_abnormal_information.modified_time
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.modified_time
     *
     * @param modifiedTime the value for media_device_abnormal_information.modified_time
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setModifiedTime(Integer modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.create_person
     *
     * @return the value of media_device_abnormal_information.create_person
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.create_person
     *
     * @param createPerson the value for media_device_abnormal_information.create_person
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.create_time
     *
     * @return the value of media_device_abnormal_information.create_time
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.create_time
     *
     * @param createTime the value for media_device_abnormal_information.create_time
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.department
     *
     * @return the value of media_device_abnormal_information.department
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.department
     *
     * @param department the value for media_device_abnormal_information.department
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_1
     *
     * @return the value of media_device_abnormal_information.retain_1
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain1() {
        return retain1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_1
     *
     * @param retain1 the value for media_device_abnormal_information.retain_1
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain1(String retain1) {
        this.retain1 = retain1 == null ? null : retain1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_2
     *
     * @return the value of media_device_abnormal_information.retain_2
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain2() {
        return retain2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_2
     *
     * @param retain2 the value for media_device_abnormal_information.retain_2
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain2(String retain2) {
        this.retain2 = retain2 == null ? null : retain2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_3
     *
     * @return the value of media_device_abnormal_information.retain_3
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain3() {
        return retain3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_3
     *
     * @param retain3 the value for media_device_abnormal_information.retain_3
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain3(String retain3) {
        this.retain3 = retain3 == null ? null : retain3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_4
     *
     * @return the value of media_device_abnormal_information.retain_4
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain4() {
        return retain4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_4
     *
     * @param retain4 the value for media_device_abnormal_information.retain_4
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain4(String retain4) {
        this.retain4 = retain4 == null ? null : retain4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_5
     *
     * @return the value of media_device_abnormal_information.retain_5
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain5() {
        return retain5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_5
     *
     * @param retain5 the value for media_device_abnormal_information.retain_5
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain5(String retain5) {
        this.retain5 = retain5 == null ? null : retain5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_6
     *
     * @return the value of media_device_abnormal_information.retain_6
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain6() {
        return retain6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_6
     *
     * @param retain6 the value for media_device_abnormal_information.retain_6
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain6(String retain6) {
        this.retain6 = retain6 == null ? null : retain6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_7
     *
     * @return the value of media_device_abnormal_information.retain_7
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getRetain7() {
        return retain7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_7
     *
     * @param retain7 the value for media_device_abnormal_information.retain_7
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain7(String retain7) {
        this.retain7 = retain7 == null ? null : retain7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_8
     *
     * @return the value of media_device_abnormal_information.retain_8
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getRetain8() {
        return retain8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_8
     *
     * @param retain8 the value for media_device_abnormal_information.retain_8
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain8(Integer retain8) {
        this.retain8 = retain8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_9
     *
     * @return the value of media_device_abnormal_information.retain_9
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getRetain9() {
        return retain9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_9
     *
     * @param retain9 the value for media_device_abnormal_information.retain_9
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain9(Integer retain9) {
        this.retain9 = retain9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.retain_10
     *
     * @return the value of media_device_abnormal_information.retain_10
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getRetain10() {
        return retain10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.retain_10
     *
     * @param retain10 the value for media_device_abnormal_information.retain_10
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setRetain10(Integer retain10) {
        this.retain10 = retain10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.adcode
     *
     * @return the value of media_device_abnormal_information.adcode
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getAdcode() {
        return adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.adcode
     *
     * @param adcode the value for media_device_abnormal_information.adcode
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode == null ? null : adcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.province
     *
     * @return the value of media_device_abnormal_information.province
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.province
     *
     * @param province the value for media_device_abnormal_information.province
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.city
     *
     * @return the value of media_device_abnormal_information.city
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.city
     *
     * @param city the value for media_device_abnormal_information.city
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.area
     *
     * @return the value of media_device_abnormal_information.area
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.area
     *
     * @param area the value for media_device_abnormal_information.area
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.property_number
     *
     * @return the value of media_device_abnormal_information.property_number
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getPropertyNumber() {
        return propertyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.property_number
     *
     * @param propertyNumber the value for media_device_abnormal_information.property_number
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setPropertyNumber(String propertyNumber) {
        this.propertyNumber = propertyNumber == null ? null : propertyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.dev_name
     *
     * @return the value of media_device_abnormal_information.dev_name
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getDevName() {
        return devName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.dev_name
     *
     * @param devName the value for media_device_abnormal_information.dev_name
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setDevName(String devName) {
        this.devName = devName == null ? null : devName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.media_resource_status
     *
     * @return the value of media_device_abnormal_information.media_resource_status
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getMediaResourceStatus() {
        return mediaResourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.media_resource_status
     *
     * @param mediaResourceStatus the value for media_device_abnormal_information.media_resource_status
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setMediaResourceStatus(String mediaResourceStatus) {
        this.mediaResourceStatus = mediaResourceStatus == null ? null : mediaResourceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.dev_type
     *
     * @return the value of media_device_abnormal_information.dev_type
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getDevType() {
        return devType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.dev_type
     *
     * @param devType the value for media_device_abnormal_information.dev_type
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setDevType(String devType) {
        this.devType = devType == null ? null : devType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.dev_version
     *
     * @return the value of media_device_abnormal_information.dev_version
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getDevVersion() {
        return devVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.dev_version
     *
     * @param devVersion the value for media_device_abnormal_information.dev_version
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setDevVersion(String devVersion) {
        this.devVersion = devVersion == null ? null : devVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.dev_install_model
     *
     * @return the value of media_device_abnormal_information.dev_install_model
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getDevInstallModel() {
        return devInstallModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.dev_install_model
     *
     * @param devInstallModel the value for media_device_abnormal_information.dev_install_model
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setDevInstallModel(String devInstallModel) {
        this.devInstallModel = devInstallModel == null ? null : devInstallModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.mac
     *
     * @return the value of media_device_abnormal_information.mac
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.mac
     *
     * @param mac the value for media_device_abnormal_information.mac
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.address
     *
     * @return the value of media_device_abnormal_information.address
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.address
     *
     * @param address the value for media_device_abnormal_information.address
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.s_lant
     *
     * @return the value of media_device_abnormal_information.s_lant
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getsLant() {
        return sLant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.s_lant
     *
     * @param sLant the value for media_device_abnormal_information.s_lant
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setsLant(String sLant) {
        this.sLant = sLant == null ? null : sLant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.resolution
     *
     * @return the value of media_device_abnormal_information.resolution
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.resolution
     *
     * @param resolution the value for media_device_abnormal_information.resolution
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.trade
     *
     * @return the value of media_device_abnormal_information.trade
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.trade
     *
     * @param trade the value for media_device_abnormal_information.trade
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.seller_name
     *
     * @return the value of media_device_abnormal_information.seller_name
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.seller_name
     *
     * @param sellerName the value for media_device_abnormal_information.seller_name
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.seller_type
     *
     * @return the value of media_device_abnormal_information.seller_type
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getSellerType() {
        return sellerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.seller_type
     *
     * @param sellerType the value for media_device_abnormal_information.seller_type
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setSellerType(String sellerType) {
        this.sellerType = sellerType == null ? null : sellerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.business_area
     *
     * @return the value of media_device_abnormal_information.business_area
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getBusinessArea() {
        return businessArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.business_area
     *
     * @param businessArea the value for media_device_abnormal_information.business_area
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setBusinessArea(String businessArea) {
        this.businessArea = businessArea == null ? null : businessArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.avg_price
     *
     * @return the value of media_device_abnormal_information.avg_price
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Integer getAvgPrice() {
        return avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.avg_price
     *
     * @param avgPrice the value for media_device_abnormal_information.avg_price
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setAvgPrice(Integer avgPrice) {
        this.avgPrice = avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.network
     *
     * @return the value of media_device_abnormal_information.network
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getNetwork() {
        return network;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.network
     *
     * @param network the value for media_device_abnormal_information.network
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setNetwork(String network) {
        this.network = network == null ? null : network.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.quality
     *
     * @return the value of media_device_abnormal_information.quality
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.quality
     *
     * @param quality the value for media_device_abnormal_information.quality
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.daily_customer_flow
     *
     * @return the value of media_device_abnormal_information.daily_customer_flow
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Double getDailyCustomerFlow() {
        return dailyCustomerFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.daily_customer_flow
     *
     * @param dailyCustomerFlow the value for media_device_abnormal_information.daily_customer_flow
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setDailyCustomerFlow(Double dailyCustomerFlow) {
        this.dailyCustomerFlow = dailyCustomerFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.photo
     *
     * @return the value of media_device_abnormal_information.photo
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public Object getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.photo
     *
     * @param photo the value for media_device_abnormal_information.photo
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setPhoto(Object photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.enterpriseStatus
     *
     * @return the value of media_device_abnormal_information.enterpriseStatus
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getEnterprisestatus() {
        return enterprisestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.enterpriseStatus
     *
     * @param enterprisestatus the value for media_device_abnormal_information.enterpriseStatus
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setEnterprisestatus(String enterprisestatus) {
        this.enterprisestatus = enterprisestatus == null ? null : enterprisestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_device_abnormal_information.fault
     *
     * @return the value of media_device_abnormal_information.fault
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public String getFault() {
        return fault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_device_abnormal_information.fault
     *
     * @param fault the value for media_device_abnormal_information.fault
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    public void setFault(String fault) {
        this.fault = fault == null ? null : fault.trim();
    }
}