package com.point.cart.model;

import java.util.ArrayList;
import java.util.List;

public class CartPointExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public CartPointExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCartPointIdIsNull() {
            addCriterion("cart_point_id is null");
            return (Criteria) this;
        }

        public Criteria andCartPointIdIsNotNull() {
            addCriterion("cart_point_id is not null");
            return (Criteria) this;
        }

        public Criteria andCartPointIdEqualTo(Integer value) {
            addCriterion("cart_point_id =", value, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdNotEqualTo(Integer value) {
            addCriterion("cart_point_id <>", value, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdGreaterThan(Integer value) {
            addCriterion("cart_point_id >", value, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cart_point_id >=", value, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdLessThan(Integer value) {
            addCriterion("cart_point_id <", value, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdLessThanOrEqualTo(Integer value) {
            addCriterion("cart_point_id <=", value, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdIn(List<Integer> values) {
            addCriterion("cart_point_id in", values, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdNotIn(List<Integer> values) {
            addCriterion("cart_point_id not in", values, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdBetween(Integer value1, Integer value2) {
            addCriterion("cart_point_id between", value1, value2, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartPointIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cart_point_id not between", value1, value2, "cartPointId");
            return (Criteria) this;
        }

        public Criteria andCartNumberIsNull() {
            addCriterion("cart_number is null");
            return (Criteria) this;
        }

        public Criteria andCartNumberIsNotNull() {
            addCriterion("cart_number is not null");
            return (Criteria) this;
        }

        public Criteria andCartNumberEqualTo(String value) {
            addCriterion("cart_number =", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberNotEqualTo(String value) {
            addCriterion("cart_number <>", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberGreaterThan(String value) {
            addCriterion("cart_number >", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberGreaterThanOrEqualTo(String value) {
            addCriterion("cart_number >=", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberLessThan(String value) {
            addCriterion("cart_number <", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberLessThanOrEqualTo(String value) {
            addCriterion("cart_number <=", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberLike(String value) {
            addCriterion("cart_number like", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberNotLike(String value) {
            addCriterion("cart_number not like", value, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberIn(List<String> values) {
            addCriterion("cart_number in", values, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberNotIn(List<String> values) {
            addCriterion("cart_number not in", values, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberBetween(String value1, String value2) {
            addCriterion("cart_number between", value1, value2, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andCartNumberNotBetween(String value1, String value2) {
            addCriterion("cart_number not between", value1, value2, "cartNumber");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTimeIdIsNull() {
            addCriterion("time_id is null");
            return (Criteria) this;
        }

        public Criteria andTimeIdIsNotNull() {
            addCriterion("time_id is not null");
            return (Criteria) this;
        }

        public Criteria andTimeIdEqualTo(Integer value) {
            addCriterion("time_id =", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdNotEqualTo(Integer value) {
            addCriterion("time_id <>", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdGreaterThan(Integer value) {
            addCriterion("time_id >", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_id >=", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdLessThan(Integer value) {
            addCriterion("time_id <", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdLessThanOrEqualTo(Integer value) {
            addCriterion("time_id <=", value, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdIn(List<Integer> values) {
            addCriterion("time_id in", values, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdNotIn(List<Integer> values) {
            addCriterion("time_id not in", values, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdBetween(Integer value1, Integer value2) {
            addCriterion("time_id between", value1, value2, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("time_id not between", value1, value2, "timeId");
            return (Criteria) this;
        }

        public Criteria andTimeLengthIsNull() {
            addCriterion("time_length is null");
            return (Criteria) this;
        }

        public Criteria andTimeLengthIsNotNull() {
            addCriterion("time_length is not null");
            return (Criteria) this;
        }

        public Criteria andTimeLengthEqualTo(Integer value) {
            addCriterion("time_length =", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotEqualTo(Integer value) {
            addCriterion("time_length <>", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthGreaterThan(Integer value) {
            addCriterion("time_length >", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_length >=", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthLessThan(Integer value) {
            addCriterion("time_length <", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthLessThanOrEqualTo(Integer value) {
            addCriterion("time_length <=", value, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthIn(List<Integer> values) {
            addCriterion("time_length in", values, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotIn(List<Integer> values) {
            addCriterion("time_length not in", values, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthBetween(Integer value1, Integer value2) {
            addCriterion("time_length between", value1, value2, "timeLength");
            return (Criteria) this;
        }

        public Criteria andTimeLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("time_length not between", value1, value2, "timeLength");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNull() {
            addCriterion("city_code is null");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNotNull() {
            addCriterion("city_code is not null");
            return (Criteria) this;
        }

        public Criteria andCityCodeEqualTo(String value) {
            addCriterion("city_code =", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotEqualTo(String value) {
            addCriterion("city_code <>", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThan(String value) {
            addCriterion("city_code >", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("city_code >=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThan(String value) {
            addCriterion("city_code <", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThanOrEqualTo(String value) {
            addCriterion("city_code <=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLike(String value) {
            addCriterion("city_code like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotLike(String value) {
            addCriterion("city_code not like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeIn(List<String> values) {
            addCriterion("city_code in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotIn(List<String> values) {
            addCriterion("city_code not in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeBetween(String value1, String value2) {
            addCriterion("city_code between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotBetween(String value1, String value2) {
            addCriterion("city_code not between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("city_name is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("city_name is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("city_name =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("city_name <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("city_name >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("city_name >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("city_name <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("city_name <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("city_name like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("city_name not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("city_name in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("city_name not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("city_name between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("city_name not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andScreenNumberIsNull() {
            addCriterion("screen_number is null");
            return (Criteria) this;
        }

        public Criteria andScreenNumberIsNotNull() {
            addCriterion("screen_number is not null");
            return (Criteria) this;
        }

        public Criteria andScreenNumberEqualTo(String value) {
            addCriterion("screen_number =", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberNotEqualTo(String value) {
            addCriterion("screen_number <>", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberGreaterThan(String value) {
            addCriterion("screen_number >", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberGreaterThanOrEqualTo(String value) {
            addCriterion("screen_number >=", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberLessThan(String value) {
            addCriterion("screen_number <", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberLessThanOrEqualTo(String value) {
            addCriterion("screen_number <=", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberLike(String value) {
            addCriterion("screen_number like", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberNotLike(String value) {
            addCriterion("screen_number not like", value, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberIn(List<String> values) {
            addCriterion("screen_number in", values, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberNotIn(List<String> values) {
            addCriterion("screen_number not in", values, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberBetween(String value1, String value2) {
            addCriterion("screen_number between", value1, value2, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andScreenNumberNotBetween(String value1, String value2) {
            addCriterion("screen_number not between", value1, value2, "screenNumber");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<Integer> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<Integer> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andPurposeIsNull() {
            addCriterion("purpose is null");
            return (Criteria) this;
        }

        public Criteria andPurposeIsNotNull() {
            addCriterion("purpose is not null");
            return (Criteria) this;
        }

        public Criteria andPurposeEqualTo(Integer value) {
            addCriterion("purpose =", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotEqualTo(Integer value) {
            addCriterion("purpose <>", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeGreaterThan(Integer value) {
            addCriterion("purpose >", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeGreaterThanOrEqualTo(Integer value) {
            addCriterion("purpose >=", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLessThan(Integer value) {
            addCriterion("purpose <", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLessThanOrEqualTo(Integer value) {
            addCriterion("purpose <=", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeIn(List<Integer> values) {
            addCriterion("purpose in", values, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotIn(List<Integer> values) {
            addCriterion("purpose not in", values, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeBetween(Integer value1, Integer value2) {
            addCriterion("purpose between", value1, value2, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotBetween(Integer value1, Integer value2) {
            addCriterion("purpose not between", value1, value2, "purpose");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Long value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Long value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Long value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Long value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Long value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Long> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Long> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Long value1, Long value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Long value1, Long value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Long value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Long value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Long value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Long value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Long value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Long> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Long> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Long value1, Long value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Long value1, Long value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andTimeBucketIsNull() {
            addCriterion("time_bucket is null");
            return (Criteria) this;
        }

        public Criteria andTimeBucketIsNotNull() {
            addCriterion("time_bucket is not null");
            return (Criteria) this;
        }

        public Criteria andTimeBucketEqualTo(String value) {
            addCriterion("time_bucket =", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketNotEqualTo(String value) {
            addCriterion("time_bucket <>", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketGreaterThan(String value) {
            addCriterion("time_bucket >", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketGreaterThanOrEqualTo(String value) {
            addCriterion("time_bucket >=", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketLessThan(String value) {
            addCriterion("time_bucket <", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketLessThanOrEqualTo(String value) {
            addCriterion("time_bucket <=", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketLike(String value) {
            addCriterion("time_bucket like", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketNotLike(String value) {
            addCriterion("time_bucket not like", value, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketIn(List<String> values) {
            addCriterion("time_bucket in", values, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketNotIn(List<String> values) {
            addCriterion("time_bucket not in", values, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketBetween(String value1, String value2) {
            addCriterion("time_bucket between", value1, value2, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andTimeBucketNotBetween(String value1, String value2) {
            addCriterion("time_bucket not between", value1, value2, "timeBucket");
            return (Criteria) this;
        }

        public Criteria andSelectModeIsNull() {
            addCriterion("select_mode is null");
            return (Criteria) this;
        }

        public Criteria andSelectModeIsNotNull() {
            addCriterion("select_mode is not null");
            return (Criteria) this;
        }

        public Criteria andSelectModeEqualTo(Integer value) {
            addCriterion("select_mode =", value, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeNotEqualTo(Integer value) {
            addCriterion("select_mode <>", value, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeGreaterThan(Integer value) {
            addCriterion("select_mode >", value, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_mode >=", value, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeLessThan(Integer value) {
            addCriterion("select_mode <", value, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeLessThanOrEqualTo(Integer value) {
            addCriterion("select_mode <=", value, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeIn(List<Integer> values) {
            addCriterion("select_mode in", values, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeNotIn(List<Integer> values) {
            addCriterion("select_mode not in", values, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeBetween(Integer value1, Integer value2) {
            addCriterion("select_mode between", value1, value2, "selectMode");
            return (Criteria) this;
        }

        public Criteria andSelectModeNotBetween(Integer value1, Integer value2) {
            addCriterion("select_mode not between", value1, value2, "selectMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeIsNull() {
            addCriterion("play_mode is null");
            return (Criteria) this;
        }

        public Criteria andPlayModeIsNotNull() {
            addCriterion("play_mode is not null");
            return (Criteria) this;
        }

        public Criteria andPlayModeEqualTo(Integer value) {
            addCriterion("play_mode =", value, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeNotEqualTo(Integer value) {
            addCriterion("play_mode <>", value, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeGreaterThan(Integer value) {
            addCriterion("play_mode >", value, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("play_mode >=", value, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeLessThan(Integer value) {
            addCriterion("play_mode <", value, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeLessThanOrEqualTo(Integer value) {
            addCriterion("play_mode <=", value, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeIn(List<Integer> values) {
            addCriterion("play_mode in", values, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeNotIn(List<Integer> values) {
            addCriterion("play_mode not in", values, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeBetween(Integer value1, Integer value2) {
            addCriterion("play_mode between", value1, value2, "playMode");
            return (Criteria) this;
        }

        public Criteria andPlayModeNotBetween(Integer value1, Integer value2) {
            addCriterion("play_mode not between", value1, value2, "playMode");
            return (Criteria) this;
        }

        public Criteria andSystemIsNull() {
            addCriterion("system is null");
            return (Criteria) this;
        }

        public Criteria andSystemIsNotNull() {
            addCriterion("system is not null");
            return (Criteria) this;
        }

        public Criteria andSystemEqualTo(Integer value) {
            addCriterion("system =", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotEqualTo(Integer value) {
            addCriterion("system <>", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThan(Integer value) {
            addCriterion("system >", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThanOrEqualTo(Integer value) {
            addCriterion("system >=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThan(Integer value) {
            addCriterion("system <", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThanOrEqualTo(Integer value) {
            addCriterion("system <=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemIn(List<Integer> values) {
            addCriterion("system in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotIn(List<Integer> values) {
            addCriterion("system not in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemBetween(Integer value1, Integer value2) {
            addCriterion("system between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotBetween(Integer value1, Integer value2) {
            addCriterion("system not between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andPointTypeIsNull() {
            addCriterion("point_type is null");
            return (Criteria) this;
        }

        public Criteria andPointTypeIsNotNull() {
            addCriterion("point_type is not null");
            return (Criteria) this;
        }

        public Criteria andPointTypeEqualTo(Integer value) {
            addCriterion("point_type =", value, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeNotEqualTo(Integer value) {
            addCriterion("point_type <>", value, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeGreaterThan(Integer value) {
            addCriterion("point_type >", value, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("point_type >=", value, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeLessThan(Integer value) {
            addCriterion("point_type <", value, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeLessThanOrEqualTo(Integer value) {
            addCriterion("point_type <=", value, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeIn(List<Integer> values) {
            addCriterion("point_type in", values, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeNotIn(List<Integer> values) {
            addCriterion("point_type not in", values, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeBetween(Integer value1, Integer value2) {
            addCriterion("point_type between", value1, value2, "pointType");
            return (Criteria) this;
        }

        public Criteria andPointTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("point_type not between", value1, value2, "pointType");
            return (Criteria) this;
        }

        public Criteria andTimeTotalIsNull() {
            addCriterion("time_total is null");
            return (Criteria) this;
        }

        public Criteria andTimeTotalIsNotNull() {
            addCriterion("time_total is not null");
            return (Criteria) this;
        }

        public Criteria andTimeTotalEqualTo(Integer value) {
            addCriterion("time_total =", value, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalNotEqualTo(Integer value) {
            addCriterion("time_total <>", value, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalGreaterThan(Integer value) {
            addCriterion("time_total >", value, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_total >=", value, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalLessThan(Integer value) {
            addCriterion("time_total <", value, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalLessThanOrEqualTo(Integer value) {
            addCriterion("time_total <=", value, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalIn(List<Integer> values) {
            addCriterion("time_total in", values, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalNotIn(List<Integer> values) {
            addCriterion("time_total not in", values, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalBetween(Integer value1, Integer value2) {
            addCriterion("time_total between", value1, value2, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andTimeTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("time_total not between", value1, value2, "timeTotal");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(Integer value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(Integer value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(Integer value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(Integer value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(Integer value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<Integer> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<Integer> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(Integer value1, Integer value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cart_point
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 08 10:29:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}