server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  context-path: /pointCart

# 配置注册地址
eureka:
  instance:
    prefer-ip-address: true
    # 本机ip地址
    ip-address: 192.168.3.156
  client:
    serviceUrl:
      defaultZone: http://172.18.4.24:8761/eureka/

spring:
  # 注册服务名称
  application:
      name: point-cart-dengwei
#  数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.18.37:3433/mediav2?useUnicode=true&characterEncoding=UTF-8&allowEncodingChanges=true
    username: media
    password: Dftc1234
    type: com.alibaba.druid.pool.DruidDataSource
#  编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
      enabled: true
#  Redis
  redis:
    host: 127.0.0.1
#    host: 192.168.3.194
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 2000
#    database: 9
#    password: Dftc1234

  freemarker:
    check-template-location: false


#  Mybatis
mybatis:
  mapper-locations: classpath:xml/*.xml
  type-aliases-package: com.point.cart.model
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

#debug: true
#  日志
logging:
  file: /log/pointCart
  level:
#    root: DEBUG
#    com.point.cart.mapper=DEBUG
#    com.ibatis=DEBUG
#    com.ibatis.common.jdbc.SimpleDataSource=DEBUG
#    com.ibatis.common.jdbc.ScriptRunner=DEBUG
#    java.sql.Connection=DEBUG
#    java.sql.Statement=DEBUG
#    java.sql.PreparedStatement=DEBUG

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 10
  MaxAutoRetriesNextServer: 10
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

totalTime: 300
fileSize: 10



