package com.point.cart.mapper;

import com.point.cart.model.AbnormalCartPoint;
import com.point.cart.model.AbnormalCartPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbnormalCartPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int countByExample(AbnormalCartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int deleteByExample(AbnormalCartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int deleteByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int insert(AbnormalCartPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int insertSelective(AbnormalCartPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    List<AbnormalCartPoint> selectByExample(AbnormalCartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    AbnormalCartPoint selectByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") AbnormalCartPoint record, @Param("example") AbnormalCartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int updateByExample(@Param("record") AbnormalCartPoint record, @Param("example") AbnormalCartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int updateByPrimaryKeySelective(AbnormalCartPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_device_abnormal_information
     *
     * @mbggenerated Thu Dec 28 18:04:32 CST 2017
     */
    int updateByPrimaryKey(AbnormalCartPoint record);
}