package com.point.cart.mapper;

import com.point.cart.model.CartPoint;
import com.point.cart.model.CartPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    int countByExample(CartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    int deleteByExample(CartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    int deleteByPrimaryKey(Integer cartPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    int insert(CartPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    int insertSelective(CartPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    List<CartPoint> selectByExample(CartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    CartPoint selectByPrimaryKey(Integer cartPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") CartPoint record, @Param("example") CartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:07 CST 2018
     */
    int updateByExample(@Param("record") CartPoint record, @Param("example") CartPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:07 CST 2018
     */
    int updateByPrimaryKeySelective(CartPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart_point
     *
     * @mbggenerated Mon Jan 08 10:29:07 CST 2018
     */
    int updateByPrimaryKey(CartPoint record);
}